import rawHeroes from "../data/dotaHeroes.json";
import { NeutralItemRecommendation } from "../types/meta";

export type HeroArchetype =
  | "PhysicalCarryMelee"
  | "PhysicalCarryRanged"
  | "SpellCaster"
  | "TankInitiator"
  | "SupportUtility"
  | "UniversalAllRounder";

interface RawHeroItem {
  id: number;
  name: string;
  localized_name: string;
  primary_attr: "str" | "agi" | "int" | "all" | string;
  attack_type: "Melee" | "Ranged" | string;
  roles: string[];
}

const HEROES_LIST = rawHeroes as RawHeroItem[];
const HEROES_BY_NAME = new Map<string, RawHeroItem>();

HEROES_LIST.forEach((h) => {
  HEROES_BY_NAME.set(h.name.toLowerCase(), h);
  const clean = h.name.replace(/^npc_dota_hero_/, "").toLowerCase();
  HEROES_BY_NAME.set(clean, h);
  HEROES_BY_NAME.set(h.localized_name.toLowerCase(), h);
});

// Explicit archetype overrides for well-known heroes
const ARCHETYPE_OVERRIDES: Record<string, HeroArchetype> = {
  antimage: "PhysicalCarryMelee",
  phantom_assassin: "PhysicalCarryMelee",
  juggernaut: "PhysicalCarryMelee",
  sven: "PhysicalCarryMelee",
  slark: "PhysicalCarryMelee",
  faceless_void: "PhysicalCarryMelee",
  ursa: "PhysicalCarryMelee",
  lifestealer: "PhysicalCarryMelee",
  wraith_king: "PhysicalCarryMelee",
  bloodseeker: "PhysicalCarryMelee",
  monkey_king: "PhysicalCarryMelee",
  terrorblade: "PhysicalCarryRanged",
  drow_ranger: "PhysicalCarryRanged",
  sniper: "PhysicalCarryRanged",
  medusa: "PhysicalCarryRanged",
  clinkz: "PhysicalCarryRanged",
  luna: "PhysicalCarryRanged",
  weaver: "PhysicalCarryRanged",
  viper: "PhysicalCarryRanged",
  templar_assassin: "PhysicalCarryRanged",
  morphling: "PhysicalCarryRanged",
  invoker: "SpellCaster",
  zeus: "SpellCaster",
  lina: "SpellCaster",
  storm_spirit: "SpellCaster",
  puck: "SpellCaster",
  queenofpain: "SpellCaster",
  leshrac: "SpellCaster",
  skywrath_mage: "SpellCaster",
  tinker: "SpellCaster",
  necrolyte: "SpellCaster",
  death_prophet: "SpellCaster",
  axe: "TankInitiator",
  bristleback: "TankInitiator",
  centaur: "TankInitiator",
  tidehunter: "TankInitiator",
  mars: "TankInitiator",
  slardar: "TankInitiator",
  pudge: "TankInitiator",
  primal_beast: "TankInitiator",
  legion_commander: "TankInitiator",
  kunkka: "TankInitiator",
  dragon_knight: "TankInitiator",
  crystal_maiden: "SupportUtility",
  lion: "SupportUtility",
  witch_doctor: "SupportUtility",
  shadow_shaman: "SupportUtility",
  dazzle: "SupportUtility",
  oracle: "SupportUtility",
  jakiro: "SupportUtility",
  rubick: "SupportUtility",
  bane: "SupportUtility",
  ogre_magi: "SupportUtility",
  ancient_apparition: "SupportUtility",
  warlock: "SupportUtility",
  windrunner: "UniversalAllRounder",
  abaddon: "UniversalAllRounder",
  pangolier: "UniversalAllRounder",
  dark_willow: "UniversalAllRounder",
  enigma: "UniversalAllRounder",
  magnataur: "UniversalAllRounder",
  vengefulspirit: "UniversalAllRounder",
  bane_all: "UniversalAllRounder",
  marci: "UniversalAllRounder",
};

/**
 * Categorize a hero into one of the 6 archetypes for neutral item matching
 */
export function getHeroArchetype(heroNameOrKey: string): {
  archetype: HeroArchetype;
  displayName: string;
  roleLabelTh: string;
  roleLabelEn: string;
} {
  const clean = heroNameOrKey.replace(/^npc_dota_hero_/, "").toLowerCase();
  const hero = HEROES_BY_NAME.get(clean);

  if (ARCHETYPE_OVERRIDES[clean]) {
    const arch = ARCHETYPE_OVERRIDES[clean];
    return {
      archetype: arch,
      displayName: hero?.localized_name || clean.replace(/_/g, " "),
      ...getRoleLabels(arch),
    };
  }

  if (hero) {
    const isRanged = hero.attack_type === "Ranged";
    const isUniversal = hero.primary_attr === "all";
    const hasCarryRole = hero.roles.includes("Carry");
    const hasSupportRole = hero.roles.includes("Support");
    const hasTankRole = hero.roles.includes("Durable") || hero.roles.includes("Initiator");

    let arch: HeroArchetype;
    if (isUniversal) {
      arch = "UniversalAllRounder";
    } else if (hasCarryRole && !hasSupportRole) {
      arch = isRanged ? "PhysicalCarryRanged" : "PhysicalCarryMelee";
    } else if (hero.primary_attr === "int" || hero.roles.includes("Nuker")) {
      arch = hasSupportRole ? "SupportUtility" : "SpellCaster";
    } else if (hasTankRole || hero.primary_attr === "str") {
      arch = "TankInitiator";
    } else if (hasSupportRole) {
      arch = "SupportUtility";
    } else {
      arch = isRanged ? "PhysicalCarryRanged" : "PhysicalCarryMelee";
    }

    return {
      archetype: arch,
      displayName: hero.localized_name,
      ...getRoleLabels(arch),
    };
  }

  // Default fallback
  return {
    archetype: "PhysicalCarryMelee",
    displayName: clean ? clean.replace(/_/g, " ") : "Hero",
    roleLabelTh: "แครี่ / โจมตีประชิด",
    roleLabelEn: "Physical Carry (Melee)",
  };
}

/**
 * Determines if a hero is typically played as Support (Pos 4 / Pos 5)
 */
export function isSupportHero(heroNameOrKey: string): boolean {
  if (!heroNameOrKey) return false;
  const clean = heroNameOrKey.replace(/^npc_dota_hero_/, "").toLowerCase();
  const info = getHeroArchetype(clean);
  if (info.archetype === "SupportUtility") {
    return true;
  }
  const hero = HEROES_BY_NAME.get(clean);
  return Boolean(hero?.roles?.includes("Support"));
}

function getRoleLabels(arch: HeroArchetype) {
  switch (arch) {
    case "PhysicalCarryMelee":
      return { roleLabelTh: "แครี่ / โจมตีประชิด", roleLabelEn: "Physical Carry (Melee)" };
    case "PhysicalCarryRanged":
      return { roleLabelTh: "แครี่ / โจมตีระยะไกล", roleLabelEn: "Physical Carry (Ranged)" };
    case "SpellCaster":
      return { roleLabelTh: "เวท / นุ๊กเกอร์", roleLabelEn: "Spell Caster / Nuker" };
    case "TankInitiator":
      return { roleLabelTh: "แทงก์ / ตัวเปิดไฟต์", roleLabelEn: "Tank / Initiator" };
    case "SupportUtility":
      return { roleLabelTh: "ซัพพอร์ต / ยูทิลิตี้", roleLabelEn: "Support / Utility" };
    case "UniversalAllRounder":
      return { roleLabelTh: "ยูนิเวอร์แซล / รอบด้าน", roleLabelEn: "Universal / Flex" };
  }
}

// Master Tier-ranked database by Hero Archetype
type ArchetypeRankings = Record<HeroArchetype, NeutralItemRecommendation[]>;

const NEUTRAL_TIER_DATABASE: Record<number, ArchetypeRankings> = {
  // === TIER 1 (7:00) ===
  1: {
    PhysicalCarryMelee: [
      {
        key: "broom_handle",
        displayName: "Broom Handle",
        tier: 1,
        score: 95,
        tierRank: "S",
        reasonTh: "เพิ่มระยะฟัน +50, ดาเมจ +8 และเกราะ +4 ยืนเทรดและฟาร์มสบายมาก",
        reasonEn: "+50 Melee range, +8 Damage, +4 Armor. Superb early trading and farming.",
        statsSummary: "+50 Range, +8 Dmg, +4 Armor",
      },
      {
        key: "duelist_gloves",
        displayName: "Duelist Gloves",
        tier: 1,
        score: 90,
        tierRank: "S",
        reasonTh: "เพิ่มความเร็วโจมตี +10 และบวกเพิ่มอีก +15 เมื่อศัตรูอยู่ใกล้ ตีไวสุดๆ",
        reasonEn: "+10 Attack speed (+15 bonus near enemies). Maximizes hit rate and proc chances.",
        statsSummary: "+10 to +25 Attack Speed",
      },
      {
        key: "occult_bracelet",
        displayName: "Occult Bracelet",
        tier: 1,
        score: 82,
        tierRank: "A",
        reasonTh: "+3 สเตตัสทุกค่า สะสมรีเจนมานาและกันเวทเมื่อโดนตี ฟาร์มต่อเนื่องมานาไม่แห้ง",
        reasonEn: "+3 All stats, stacks magic resist & mana regen when struck. Endless farm sustain.",
        statsSummary: "+3 All Stats, Mana/MR Stacks",
      },
      {
        key: "safety_bubble",
        displayName: "Safety Bubble",
        tier: 1,
        score: 78,
        tierRank: "A",
        reasonTh: "+100 HP และบาเรีย 100 HP ป้องกันการโดนตอดเลือดและเบิสต์ตายต้นเกม",
        reasonEn: "+100 HP & 100 HP barrier. Prevents lane harass and gank bursts.",
        statsSummary: "+100 HP, 100 HP Barrier",
      },
      {
        key: "royal_jelly",
        displayName: "Royal Jelly",
        tier: 1,
        score: 68,
        tierRank: "B",
        reasonTh: "+50 HP และมานา กดกินเพิ่มรีเจนถาวรให้ตนเองและเพื่อน",
        reasonEn: "+50 HP & Mana, grants passive HP/Mana regen buff to you and ally.",
        statsSummary: "+50 HP/Mana, Regen Buff",
      },
    ],
    PhysicalCarryRanged: [
      {
        key: "duelist_gloves",
        displayName: "Duelist Gloves",
        tier: 1,
        score: 94,
        tierRank: "S",
        reasonTh: "เพิ่มความเร็วโจมตีสูง ยิงรัวเก็บครีปและรีดดาเมจใส่ศัตรู",
        reasonEn: "+10 to +25 Attack Speed. Huge early DPS spike for ranged right-clickers.",
        statsSummary: "+10 to +25 Attack Speed",
      },
      {
        key: "occult_bracelet",
        displayName: "Occult Bracelet",
        tier: 1,
        score: 88,
        tierRank: "S",
        reasonTh: "+3 สเตตัสทุกค่า ได้ทั้งดาเมจ เลือด และรีเจนมานาสำหรับกดสกิลฟาร์ม",
        reasonEn: "+3 All stats, stacks mana regen and magic resistance.",
        statsSummary: "+3 All Stats, Mana Sustain",
      },
      {
        key: "spark_of_courage",
        displayName: "Spark of Courage",
        tier: 1,
        score: 82,
        tierRank: "A",
        reasonTh: "+10 ดาเมจเมื่อเลือดเกิน 50% ช่วยให้ Last Hit แม่นยำและยิงกดดันเลนแรง",
        reasonEn: "+10 Damage when above 50% HP. Sharp last hitting and lane pressure.",
        statsSummary: "+10 Dmg / +5 Armor",
      },
      {
        key: "safety_bubble",
        displayName: "Safety Bubble",
        tier: 1,
        score: 76,
        tierRank: "A",
        reasonTh: "+100 HP และบาเรียดูดซับดาเมจ ป้องกันตัวบางโดนกระโดดจับ",
        reasonEn: "+100 HP & 100 HP barrier. Vital safety net for squishy ranged cores.",
        statsSummary: "+100 HP, 100 HP Barrier",
      },
      {
        key: "royal_jelly",
        displayName: "Royal Jelly",
        tier: 1,
        score: 68,
        tierRank: "B",
        reasonTh: "เพิ่มค่าเลือดและมานาพร้อมบัฟรีเจนสำหรับยืนเลน",
        reasonEn: "+50 HP/Mana with shared sustain regeneration.",
        statsSummary: "+50 HP/Mana, Regen",
      },
    ],
    SpellCaster: [
      {
        key: "arcane_ring",
        displayName: "Arcane Ring",
        tier: 1,
        score: 96,
        tierRank: "S",
        reasonTh: "+7 Int, +2 Armor, กดแจกมานา 45 ทันที สแปมสกิลตอดศัตรูได้ต่อเนื่อง",
        reasonEn: "+7 Int, +2 Armor, active restores 45 mana. Non-stop spell harassment.",
        statsSummary: "+7 Int, +2 Armor, 45 Mana Active",
      },
      {
        key: "occult_bracelet",
        displayName: "Occult Bracelet",
        tier: 1,
        score: 86,
        tierRank: "S",
        reasonTh: "+3 All Stats, รีเจนมานาและกันเวทช่วยให้ยืนเทรดสกิลได้อย่างปลอดภัย",
        reasonEn: "+3 All stats with stacking mana regeneration and magic resistance.",
        statsSummary: "+3 All Stats, Mana Regen Stacks",
      },
      {
        key: "safety_bubble",
        displayName: "Safety Bubble",
        tier: 1,
        score: 80,
        tierRank: "A",
        reasonTh: "บาเรีย 100 HP ป้องกันการโดนเบิสต์และไม่ให้การร่ายสกิลถูกขัดจังหวะง่ายๆ",
        reasonEn: "100 HP barrier protects fragile casters from sudden burst damage.",
        statsSummary: "+100 HP, 100 HP Barrier",
      },
      {
        key: "royal_jelly",
        displayName: "Royal Jelly",
        tier: 1,
        score: 75,
        tierRank: "A",
        reasonTh: "+50 HP/Mana และบัฟรีเจนเพื่อการคุมเลนและเดินเกม",
        reasonEn: "+50 HP/Mana with sustain regeneration.",
        statsSummary: "+50 HP/Mana, Regen",
      },
      {
        key: "trusty_shovel",
        displayName: "Trusty Shovel",
        tier: 1,
        score: 65,
        tierRank: "B",
        reasonTh: "+75 HP กดขุดหาน้ำส้ม/รูนทอง/มะม่วงมานา",
        reasonEn: "+75 HP, active digs for bounty runes, salves, and mangoes.",
        statsSummary: "+75 HP, Dig Active",
      },
    ],
    TankInitiator: [
      {
        key: "seeds_of_serenity",
        displayName: "Seeds of Serenity",
        tier: 1,
        score: 94,
        tierRank: "S",
        reasonTh: "+150 HP, กดสร้างออร่าฮีล +8 HP/s ยืนชนแนวหน้าและเทรดเลือดไม่มีถอย",
        reasonEn: "+150 HP, active heals allies for +8 HP/s. Unmatched early tankiness.",
        statsSummary: "+150 HP, +8 HP/s AoE Heal",
      },
      {
        key: "spark_of_courage",
        displayName: "Spark of Courage",
        tier: 1,
        score: 88,
        tierRank: "S",
        reasonTh: "+5 เกราะตอนเลือดต่ำกว่าครึ่ง เพิ่มความถึกสุดๆ หรือ +10 ดาเมจตอนเลือดเต็ม",
        reasonEn: "+5 Armor when below 50% HP or +10 Damage. Perfect for front-line brawlers.",
        statsSummary: "+5 Armor / +10 Damage",
      },
      {
        key: "broom_handle",
        displayName: "Broom Handle",
        tier: 1,
        score: 82,
        tierRank: "A",
        reasonTh: "+4 Armor และ +8 ดาเมจ เพิ่มทั้งพลังป้องกันและพลังโจมตี",
        reasonEn: "+4 Armor, +8 Damage, +50 Melee range.",
        statsSummary: "+4 Armor, +8 Dmg, +50 Range",
      },
      {
        key: "occult_bracelet",
        displayName: "Occult Bracelet",
        tier: 1,
        score: 76,
        tierRank: "A",
        reasonTh: "รับดาเมจแล้วเด้งมานากลับมาให้กดสกิลเปิดไฟต์ต่อเนื่อง",
        reasonEn: "Takes hits to generate mana regen and magic resistance.",
        statsSummary: "+3 All Stats, Mana/MR Stacks",
      },
      {
        key: "safety_bubble",
        displayName: "Safety Bubble",
        tier: 1,
        score: 70,
        tierRank: "B",
        reasonTh: "+100 HP และบาเรีย 100 HP",
        reasonEn: "+100 HP & 100 HP barrier.",
        statsSummary: "+100 HP, 100 Barrier",
      },
    ],
    SupportUtility: [
      {
        key: "arcane_ring",
        displayName: "Arcane Ring",
        tier: 1,
        score: 95,
        tierRank: "S",
        reasonTh: "+7 Int, +2 Armor, กดแจกมานา 45 ให้เพื่อนทั้งเลน ช่วยให้แครี่กดสกิลสบาย",
        reasonEn: "+7 Int, +2 Armor, active restores 45 mana to allies. Keeps lane partners loaded.",
        statsSummary: "+7 Int, +2 Armor, 45 AoE Mana",
      },
      {
        key: "trusty_shovel",
        displayName: "Trusty Shovel",
        tier: 1,
        score: 90,
        tierRank: "S",
        reasonTh: "+75 HP, ขุดหา Bounty Rune เพิ่มเงินทีม หรือยาฮีล/มะม่วงแจกเพื่อน",
        reasonEn: "+75 HP, digs up Bounty Runes, Salves, and Mangoes for the team.",
        statsSummary: "+75 HP, Resource Dig Active",
      },
      {
        key: "safety_bubble",
        displayName: "Safety Bubble",
        tier: 1,
        score: 82,
        tierRank: "A",
        reasonTh: "บาเรีย 100 HP ช่วยป้องกันซัพพอร์ตตัวบางจากการโดนฆ่าในเสี้ยววินาที",
        reasonEn: "100 HP barrier prevents fragile supports from being picked off instantly.",
        statsSummary: "+100 HP, 100 HP Barrier",
      },
      {
        key: "royal_jelly",
        displayName: "Royal Jelly",
        tier: 1,
        score: 78,
        tierRank: "A",
        reasonTh: "กดบัฟรีเจนเลือดและมานาให้แครี่ในเลน",
        reasonEn: "Buffs self and your lane core with health and mana sustain.",
        statsSummary: "+50 HP/Mana, Regen Buff",
      },
      {
        key: "pig_pole",
        displayName: "Pig Pole",
        tier: 1,
        score: 70,
        tierRank: "B",
        reasonTh: "+6 All Stats, กดแปลงร่างเป็นหมูวิ่งเร็วขึ้น 10% หลบหนีจังหวะโดนไดฟ์",
        reasonEn: "+6 All stats, active transforms into a pig for +10% move speed escape.",
        statsSummary: "+6 All Stats, Escape Active",
      },
    ],
    UniversalAllRounder: [
      {
        key: "pig_pole",
        displayName: "Pig Pole",
        tier: 1,
        score: 94,
        tierRank: "S",
        reasonTh: "+6 สเตตัสทุกค่า ให้ดาเมจสูงถึง +12.6 แก่ Universal พร้อมสกิลแปลงร่างวิ่งเร็ว",
        reasonEn: "+6 All stats yields +12.6 attack damage for Universal heroes plus escape active.",
        statsSummary: "+6 All Stats (+12.6 Dmg), +10% MS",
      },
      {
        key: "occult_bracelet",
        displayName: "Occult Bracelet",
        tier: 1,
        score: 90,
        tierRank: "S",
        reasonTh: "+3 All Stats (+6.3 ดาเมจ) พร้อมรีเจนมานาและกันเวท",
        reasonEn: "+3 All stats (+6.3 damage) with stacking mana and magic resist.",
        statsSummary: "+3 All Stats, Mana/MR Stacks",
      },
      {
        key: "duelist_gloves",
        displayName: "Duelist Gloves",
        tier: 1,
        score: 82,
        tierRank: "A",
        reasonTh: "เพิ่มความเร็วโจมตีสูง ยิงหรือฟันดาเมจ Universal รัวๆ",
        reasonEn: "+10 to +25 Attack speed to quickly apply high Universal base damage.",
        statsSummary: "+10 to +25 Attack Speed",
      },
      {
        key: "safety_bubble",
        displayName: "Safety Bubble",
        tier: 1,
        score: 76,
        tierRank: "A",
        reasonTh: "+100 HP และบาเรีย 100 HP",
        reasonEn: "+100 HP & 100 HP barrier.",
        statsSummary: "+100 HP, 100 Barrier",
      },
      {
        key: "arcane_ring",
        displayName: "Arcane Ring",
        tier: 1,
        score: 70,
        tierRank: "B",
        reasonTh: "เกราะ +2 และกดเติมมานา",
        reasonEn: "+2 Armor, active mana restore.",
        statsSummary: "+7 Int, +2 Armor, Mana Active",
      },
    ],
  },

  // === TIER 2 (17:00) ===
  2: {
    PhysicalCarryMelee: [
      {
        key: "vampire_fangs",
        displayName: "Vampire Fangs",
        tier: 2,
        score: 96,
        tierRank: "S",
        reasonTh: "+15% ดูดเลือด และ +300 วิชั่นกลางคืน ฟาร์มป่าเลือดเต็มตลอดเวลาและมองเห็นก่อน",
        reasonEn: "+15% Lifesteal, +300 Night vision. Infinite jungle farm sustain & night safety.",
        statsSummary: "+15% Lifesteal, +300 Night Vision",
      },
      {
        key: "orb_of_destruction",
        displayName: "Orb of Destruction",
        tier: 2,
        score: 90,
        tierRank: "S",
        reasonTh: "ตีลดเกราะศัตรู 3 หน่วยและสโลว์ 12% ไล่ตบศัตรูตายง่ายขึ้นมาก",
        reasonEn: "Attacks reduce armor by 3 and slow by 12%. Deadly ganking and catch tool.",
        statsSummary: "-3 Armor on Hit, 12% Slow",
      },
      {
        key: "pupils_gift",
        displayName: "Pupil's Gift",
        tier: 2,
        score: 84,
        tierRank: "A",
        reasonTh: "+14 สเตตัสรอง ให้ทั้งเลือดและความถึก หรือมานาในการฟาร์ม",
        reasonEn: "+14 Secondary attributes. Huge boost to HP, armor, and mana pool.",
        statsSummary: "+14 Secondary Stats",
      },
      {
        key: "light_collector",
        displayName: "Light Collector",
        tier: 2,
        score: 78,
        tierRank: "A",
        reasonTh: "+10% ความเร็วเคลื่อนที่ ฟื้นเลือดกลางวันและฟื้นมานากลางคืน",
        reasonEn: "+10% Move speed with day HP and night mana regeneration.",
        statsSummary: "+10% Move Speed, Day/Night Regen",
      },
      {
        key: "gossamer_cape",
        displayName: "Gossamer Cape",
        tier: 2,
        score: 70,
        tierRank: "B",
        reasonTh: "+20 ความเร็วเดิน และหลบการโจมตีแรกของฮีโร่ศัตรูทุก 5 วิ",
        reasonEn: "+20 Move speed, dodges first hero attack every 5s.",
        statsSummary: "+20 MS, Dodge First Attack",
      },
    ],
    PhysicalCarryRanged: [
      {
        key: "specialists_array",
        displayName: "Specialist's Array",
        tier: 2,
        score: 98,
        tierRank: "S",
        reasonTh: "+7 All Stats, +10 Dmg และยิงกระจายโดนเป้าหมายรอง 2 ตัว เร่งฟาร์มไวเป็นสองเท่า",
        reasonEn: "+7 All Stats, +10 Dmg, multi-shot attacks 2 extra targets. Massive farming acceleration.",
        statsSummary: "+7 Stats, +10 Dmg, Multi-shot",
      },
      {
        key: "vampire_fangs",
        displayName: "Vampire Fangs",
        tier: 2,
        score: 88,
        tierRank: "S",
        reasonTh: "+15% ดูดเลือด ยืนยิงฟาร์มเลือดไม่ลดและสู้ไฟต์ได้อึดขึ้น",
        reasonEn: "+15% Lifesteal, keeps HP full while clearing jungle stacks.",
        statsSummary: "+15% Lifesteal, +300 Night Vision",
      },
      {
        key: "orb_of_destruction",
        displayName: "Orb of Destruction",
        tier: 2,
        score: 84,
        tierRank: "A",
        reasonTh: "ลดเกราะศัตรู 3 และสโลว์ ยืนยิงไคท์ศัตรูไม่ให้เข้าถึงตัว",
        reasonEn: "-3 Armor and slow. Perfect for kiting aggressive enemies.",
        statsSummary: "-3 Armor on Hit, Slow",
      },
      {
        key: "pupils_gift",
        displayName: "Pupil's Gift",
        tier: 2,
        score: 80,
        tierRank: "A",
        reasonTh: "+14 สเตตัสรอง เพิ่มเลือดและเกราะ",
        reasonEn: "+14 Secondary attributes.",
        statsSummary: "+14 Secondary Stats",
      },
      {
        key: "gossamer_cape",
        displayName: "Gossamer Cape",
        tier: 2,
        score: 72,
        tierRank: "B",
        reasonTh: "หลบการโจมตีแรกของตัวล้วง",
        reasonEn: "Dodges first attack from flanking assassins.",
        statsSummary: "+20 MS, Attack Dodge",
      },
    ],
    SpellCaster: [
      {
        key: "philosophers_stone",
        displayName: "Philosopher's Stone",
        tier: 2,
        score: 95,
        tierRank: "S",
        reasonTh: "+75 GPM และ +200 มานา เร่งเงินออกไอเทมหลักกลางเกมได้ไวสุดๆ",
        reasonEn: "+75 GPM, +200 Mana. Accelerates mid-game core items dramatically.",
        statsSummary: "+75 GPM, +200 Mana",
      },
      {
        key: "eye_of_the_vizier",
        displayName: "Eye of the Vizier",
        tier: 2,
        score: 90,
        tierRank: "S",
        reasonTh: "+125 ระยะร่ายสกิล ยืนปล่อยสกิลจากระยะปลอดภัย ไม่เสี่ยงโดนสวน",
        reasonEn: "+125 Cast Range. Cast spells safely from beyond enemy initiation range.",
        statsSummary: "+125 Cast Range, -20% Max Mana",
      },
      {
        key: "vampire_fangs",
        displayName: "Vampire Fangs",
        tier: 2,
        score: 82,
        tierRank: "A",
        reasonTh: "+6% Spell Lifesteal ดูดเลือดจากดาเมจเวทที่ทำใส่ศัตรู",
        reasonEn: "+6% Spell Lifesteal, healing back tons of HP from AoE spells.",
        statsSummary: "+6% Spell Lifesteal, +15% Lifesteal",
      },
      {
        key: "bullwhip",
        displayName: "Bullwhip",
        tier: 2,
        score: 76,
        tierRank: "A",
        reasonTh: "กดเร่งสปีดวิ่งตนเอง หรือกดสโลว์ศัตรูเพื่อคอมโบสกิล",
        reasonEn: "Active grants +18% MS or slows enemy by 18%. Excellent positioning.",
        statsSummary: "+90 HP, +3 HP Regen, Whip Active",
      },
      {
        key: "light_collector",
        displayName: "Light Collector",
        tier: 2,
        score: 70,
        tierRank: "B",
        reasonTh: "+10% วิ่งเร็ว และรีเจนมานาในเวลากลางคืน",
        reasonEn: "+10% Move speed and night mana regen.",
        statsSummary: "+10% MS, Day/Night Regen",
      },
    ],
    TankInitiator: [
      {
        key: "dragon_scale",
        displayName: "Dragon Scale",
        tier: 2,
        score: 96,
        tierRank: "S",
        reasonTh: "+5 เกราะ, +5 รีเจนเลือด และการโจมตีทำให้ศัตรูติดไฟ 18 DPS หนึกและเทรดดาเมจยอดเยี่ยม",
        reasonEn: "+5 Armor, +5 HP Regen, attacks ignite for 18 DPS. Unshakable frontliner.",
        statsSummary: "+5 Armor, +5 HP/s, Afterburn",
      },
      {
        key: "vampire_fangs",
        displayName: "Vampire Fangs",
        tier: 2,
        score: 88,
        tierRank: "S",
        reasonTh: "+15% ดูดเลือดทั้งกายภาพและเวท ฮีลเลือดคืนระหว่างตะลุมบอน",
        reasonEn: "+15% Lifesteal, sustain through chaotic teamfight brawls.",
        statsSummary: "+15% Lifesteal, +6% Spell Lifesteal",
      },
      {
        key: "bullwhip",
        displayName: "Bullwhip",
        tier: 2,
        score: 82,
        tierRank: "A",
        reasonTh: "+90 HP และกดเร่งความเร็ววิ่งเข้าไปเปิดไฟต์หรือสโลว์เหยื่อ",
        reasonEn: "+90 HP, active speed burst to close gaps for initiation.",
        statsSummary: "+90 HP, Speed Burst Active",
      },
      {
        key: "pupils_gift",
        displayName: "Pupil's Gift",
        tier: 2,
        score: 78,
        tierRank: "A",
        reasonTh: "+14 สเตตัสรอง เพิ่มเกราะและมานา",
        reasonEn: "+14 Secondary stats for armor and mana reserves.",
        statsSummary: "+14 Secondary Stats",
      },
      {
        key: "orb_of_destruction",
        displayName: "Orb of Destruction",
        tier: 2,
        score: 72,
        tierRank: "B",
        reasonTh: "ตีลดเกราะและสโลว์",
        reasonEn: "-3 Armor and slow on hit.",
        statsSummary: "-3 Armor, Slow",
      },
    ],
    SupportUtility: [
      {
        key: "philosophers_stone",
        displayName: "Philosopher's Stone",
        tier: 2,
        score: 98,
        tierRank: "S",
        reasonTh: "+75 GPM และ +200 มานา สุดยอดไอเทมสำหรับซัพพอร์ต ช่วยให้มีเงินออก Glimmer/Force Staff ไวขึ้น",
        reasonEn: "+75 GPM, +200 Mana. Number 1 support item, funds wards & save items fast.",
        statsSummary: "+75 GPM, +200 Mana",
      },
      {
        key: "eye_of_the_vizier",
        displayName: "Eye of the Vizier",
        tier: 2,
        score: 92,
        tierRank: "S",
        reasonTh: "+125 ระยะร่ายสกิล ยืนเซฟเพื่อนและสตั๊นศัตรูจากแนวหลังอย่างปลอดภัย",
        reasonEn: "+125 Cast range. Safely disable and save allies from extreme range.",
        statsSummary: "+125 Cast Range",
      },
      {
        key: "bullwhip",
        displayName: "Bullwhip",
        tier: 2,
        score: 84,
        tierRank: "A",
        reasonTh: "กดเร่งความเร็วให้แครี่ไล่ฆ่า หรือกดสโลว์ศัตรูที่กำลังวิ่งหนี",
        reasonEn: "Boost ally speed to chase down kills or slow fleeing targets.",
        statsSummary: "+90 HP, Speed/Slow Whip",
      },
      {
        key: "gossamer_cape",
        displayName: "Gossamer Cape",
        tier: 2,
        score: 78,
        tierRank: "A",
        reasonTh: "หลบการโจมตีแรกของตัวล้วงศัตรู รอดจากการโดนเปิดและกดสกิลสวนทัน",
        reasonEn: "Dodges first hero attack every 5s, saving your life against jump assassins.",
        statsSummary: "+20 MS, Auto-Dodge First Hit",
      },
      {
        key: "light_collector",
        displayName: "Light Collector",
        tier: 2,
        score: 70,
        tierRank: "B",
        reasonTh: "+10% วิ่งเร็ว ปักวอร์ดและเดินซ้อนเลนคล่องตัว",
        reasonEn: "+10% Move speed for warding and roaming.",
        statsSummary: "+10% MS, Sustain Regen",
      },
    ],
    UniversalAllRounder: [
      {
        key: "pupils_gift",
        displayName: "Pupil's Gift",
        tier: 2,
        score: 98,
        tierRank: "S",
        reasonTh: "+28 สเตตัสรวม เพิ่มดาเมจมหาศาล +19.6 ให้ Universal พร้อมเลือดและเกราะ",
        reasonEn: "+28 Total stats granting a massive +19.6 attack damage to Universal heroes.",
        statsSummary: "+28 Stats (+19.6 Dmg), HP & Armor",
      },
      {
        key: "specialists_array",
        displayName: "Specialist's Array",
        tier: 2,
        score: 88,
        tierRank: "S",
        reasonTh: "+7 All Stats (+14.7 Dmg) และยิงกระจาย",
        reasonEn: "+7 All Stats (+14.7 Dmg) with multi-target attacks.",
        statsSummary: "+7 All Stats, Multi-shot",
      },
      {
        key: "philosophers_stone",
        displayName: "Philosopher's Stone",
        tier: 2,
        score: 82,
        tierRank: "A",
        reasonTh: "+75 GPM และ +200 มานา เร่งเงิน",
        reasonEn: "+75 GPM and mana boost.",
        statsSummary: "+75 GPM, +200 Mana",
      },
      {
        key: "vampire_fangs",
        displayName: "Vampire Fangs",
        tier: 2,
        score: 78,
        tierRank: "A",
        reasonTh: "+15% ดูดเลือดฟาร์ม",
        reasonEn: "+15% Lifesteal sustain.",
        statsSummary: "+15% Lifesteal, Night Vision",
      },
      {
        key: "orb_of_destruction",
        displayName: "Orb of Destruction",
        tier: 2,
        score: 72,
        tierRank: "B",
        reasonTh: "ลดเกราะและสโลว์",
        reasonEn: "-3 Armor on hit and slow.",
        statsSummary: "-3 Armor, Slow",
      },
    ],
  },

  // === TIER 3 (27:00) ===
  3: {
    PhysicalCarryMelee: [
      {
        key: "paladin_sword",
        displayName: "Paladin Sword",
        tier: 3,
        score: 98,
        tierRank: "S",
        reasonTh: "+16 ดาเมจ, +8% ดูดเลือด และเพิ่มการฮีล/ดูดเลือดอีก +14% ตีแล้วเลือดเด้งไม่ตายง่ายๆ",
        reasonEn: "+16 Dmg, +8% Lifesteal, +14% Heal/Lifesteal amp. Insane teamfight durability.",
        statsSummary: "+16 Dmg, +8% Lifesteal, +14% Amp",
      },
      {
        key: "mind_breaker",
        displayName: "Mind Breaker",
        tier: 3,
        score: 94,
        tierRank: "S",
        reasonTh: "+25 ความเร็วตี, +15 ดาเมจเวท และโจมตีติดใบ้ 1.5 วินาที สังหารฮีโร่ศัตรูก่อนกดสกิลหนี",
        reasonEn: "+25 AS, +15 Magic dmg, attacks silence target for 1.5s. Shuts down slippery targets.",
        statsSummary: "+25 AS, +15 Magic Dmg, 1.5s Silence",
      },
      {
        key: "elven_tunic",
        displayName: "Elven Tunic",
        tier: 3,
        score: 86,
        tierRank: "A",
        reasonTh: "+16% หลบหลีก, +7% วิ่งเร็ว และ +26 ตีไว ครบเครื่องทั้งสปีดและการเอาตัวรอด",
        reasonEn: "+16% Evasion, +7% MS, +26 Attack speed. Superb combat agility.",
        statsSummary: "+16% Evasion, +7% MS, +26 AS",
      },
      {
        key: "nemesis_curse",
        displayName: "Nemesis Curse",
        tier: 3,
        score: 80,
        tierRank: "A",
        reasonTh: "+35 ดาเมจ และคำสาปทำให้ศัตรูโดนดาเมจแรงขึ้นอีก 8%",
        reasonEn: "+35 Damage, curses target to take 8% amplified damage.",
        statsSummary: "+35 Dmg, +8% Dmg Taken Curse",
      },
      {
        key: "vindicators_axe",
        displayName: "Vindicator's Axe",
        tier: 3,
        score: 72,
        tierRank: "B",
        reasonTh: "+25 ความเร็วตี และได้เกราะ/ดาเมจเพิ่มเมื่อโดนใบ้หรือสตั๊น",
        reasonEn: "+25 AS, bonus damage and armor when CC'd.",
        statsSummary: "+25 AS, Bonus Stats on CC",
      },
    ],
    PhysicalCarryRanged: [
      {
        key: "enchanted_quiver",
        displayName: "Enchanted Quiver",
        tier: 3,
        score: 96,
        tierRank: "S",
        reasonTh: "+75 ระยะยิง และการยิงเปิดครั้งแรกติดโบนัสดาเมจเวท 225 ทุก 4 วินาที ตอดเลือดศัตรูหายครึ่งหลอด",
        reasonEn: "+75 Range, next attack deals +225 bonus magic burst every 4s. Savage poke damage.",
        statsSummary: "+75 Range, +225 Magic Burst Hit",
      },
      {
        key: "paladin_sword",
        displayName: "Paladin Sword",
        tier: 3,
        score: 90,
        tierRank: "S",
        reasonTh: "+16 ดาเมจ และเพิ่มอัตราดูดเลือด/ฮีล 14%",
        reasonEn: "+16 Dmg, +8% Lifesteal and heal amplification.",
        statsSummary: "+16 Dmg, Lifesteal & Heal Amp",
      },
      {
        key: "mind_breaker",
        displayName: "Mind Breaker",
        tier: 3,
        score: 86,
        tierRank: "A",
        reasonTh: "ยิงจากระยะไกลทำให้ศัตรูติดใบ้ 1.5 วินาที ขัดจังหวะสกิล",
        reasonEn: "Applies 1.5s silence from range, disrupting enemy initiations.",
        statsSummary: "+25 AS, 1.5s Silence on Hit",
      },
      {
        key: "elven_tunic",
        displayName: "Elven Tunic",
        tier: 3,
        score: 82,
        tierRank: "A",
        reasonTh: "+16% หลบหลีก และวิ่งเร็ว ไคท์ศัตรูได้คล่องตัว",
        reasonEn: "+16% Evasion, move speed, and attack speed for kiting.",
        statsSummary: "+16% Evasion, +7% MS, +26 AS",
      },
      {
        key: "nemesis_curse",
        displayName: "Nemesis Curse",
        tier: 3,
        score: 75,
        tierRank: "B",
        reasonTh: "+35 ดาเมจ และเพิ่มดาเมจที่เป้าหมายได้รับ 8%",
        reasonEn: "+35 Damage with damage amplification.",
        statsSummary: "+35 Dmg, Curse",
      },
    ],
    SpellCaster: [
      {
        key: "psychic_headband",
        displayName: "Psychic Headband",
        tier: 3,
        score: 98,
        tierRank: "S",
        reasonTh: "+12% Int, +100 ระยะร่าย และกดผลักศัตรูออกไป 400 หน่วย เอาชีวิตรอดจากตัวล้วงได้ทันที",
        reasonEn: "+12% Int, +100 Cast range, active pushes enemies away. Ultimate caster survival tool.",
        statsSummary: "+12% Int, +100 Cast Range, Push Active",
      },
      {
        key: "ceremonial_robe",
        displayName: "Ceremonial Robe",
        tier: 3,
        score: 92,
        tierRank: "S",
        reasonTh: "+250 มานา ออร่าลดต้านทานเวทศัตรู 10% และลดต้านสถานะ คอมโบเวทตายทั้งทีม",
        reasonEn: "+250 Mana, aura reduces enemy magic resist by 10% & status resist by 10%.",
        statsSummary: "+250 Mana, -10% Enemy MR/Status Aura",
      },
      {
        key: "doubloon",
        displayName: "Doubloon",
        tier: 3,
        score: 82,
        tierRank: "A",
        reasonTh: "สลับค่า 20% มานาเป็นเลือด หรือเลือดเป็นมานา ยืดหยุ่นทั้งตอนบุกและป้องกัน",
        reasonEn: "Toggles 20% max mana to health or health to mana for situational clutch.",
        statsSummary: "Mana / Health Conversion Toggle",
      },
      {
        key: "mind_breaker",
        displayName: "Mind Breaker",
        tier: 3,
        score: 76,
        tierRank: "A",
        reasonTh: "ตีติดใบ้ 1.5 วินาที ขัดจังหวะศัตรู",
        reasonEn: "Attacks silence target for 1.5s.",
        statsSummary: "+25 AS, 1.5s Silence",
      },
      {
        key: "cloak_of_flames",
        displayName: "Cloak of Flames",
        tier: 3,
        score: 70,
        tierRank: "B",
        reasonTh: "+5 เกราะ, +35% กันเวท และออร่าเผา 40 DPS",
        reasonEn: "+5 Armor, +35% Magic resist, 40 DPS burn aura.",
        statsSummary: "+5 Armor, +35% MR, Burn Aura",
      },
    ],
    TankInitiator: [
      {
        key: "cloak_of_flames",
        displayName: "Cloak of Flames",
        tier: 3,
        score: 98,
        tierRank: "S",
        reasonTh: "+5 เกราะ, +35% กันเวท และออร่าเผารอบตัว 40 DPS ยืนชนกลางดงศัตรู ดาเมจกระจาย",
        reasonEn: "+5 Armor, +35% Magic resist, 40 DPS burn aura. Melts enemies during initiation.",
        statsSummary: "+5 Armor, +35% MR, 40 DPS Radiance",
      },
      {
        key: "paladin_sword",
        displayName: "Paladin Sword",
        tier: 3,
        score: 90,
        tierRank: "S",
        reasonTh: "+14% บัฟการฮีลและการดูดเลือด ทำให้ตัวฟื้นฟูเลือดอย่าง Bristle, Axe, Slardar ถึกขึ้นเป็นทวีคูณ",
        reasonEn: "+14% Heal/Lifesteal amp. Amplifies all regenerative tank mechanics enormously.",
        statsSummary: "+16 Dmg, +14% Heal/Lifesteal Amp",
      },
      {
        key: "vindicators_axe",
        displayName: "Vindicator's Axe",
        tier: 3,
        score: 84,
        tierRank: "A",
        reasonTh: "+25 ความเร็วตี และได้เกราะ +30 ตอนโดนสตั๊น รับดาเมจชุดแรกได้สบาย",
        reasonEn: "+25 AS, grants +30 Armor when stunned. Shrugs off initiation focus.",
        statsSummary: "+25 AS, +30 Armor when Stunned",
      },
      {
        key: "nemesis_curse",
        displayName: "Nemesis Curse",
        tier: 3,
        score: 78,
        tierRank: "A",
        reasonTh: "+35 ดาเมจ และคำสาปเพิ่มดาเมจที่เป้าหมายได้รับ",
        reasonEn: "+35 Damage and +8% damage amplification debuff.",
        statsSummary: "+35 Dmg, Damage Amp Curse",
      },
      {
        key: "ceremonial_robe",
        displayName: "Ceremonial Robe",
        tier: 3,
        score: 72,
        tierRank: "B",
        reasonTh: "ออร่าลดกันเวทศัตรูรอบตัว 10%",
        reasonEn: "-10% Enemy magic resistance aura.",
        statsSummary: "-10% Enemy MR Aura",
      },
    ],
    SupportUtility: [
      {
        key: "psychic_headband",
        displayName: "Psychic Headband",
        tier: 3,
        score: 98,
        tierRank: "S",
        reasonTh: "+100 ระยะร่ายสกิล และกดผลักศัตรูออกไป 400 หน่วย สุดยอดไอเทมช่วยชีวิตซัพพอร์ต",
        reasonEn: "+100 Cast range, active pushes enemies away. Essential support self-peel.",
        statsSummary: "+100 Cast Range, 400 Push Active",
      },
      {
        key: "ceremonial_robe",
        displayName: "Ceremonial Robe",
        tier: 3,
        score: 92,
        tierRank: "S",
        reasonTh: "ออร่าลดต้านทานเวทและต้านสถานะศัตรู ช่วยให้สกิลสตั๊นนานขึ้นและเบิสต์ศัตรูลงไว",
        reasonEn: "Reduces enemy magic and status resistance by 10% in teamfights.",
        statsSummary: "-10% Enemy MR & Status Resist",
      },
      {
        key: "doubloon",
        displayName: "Doubloon",
        tier: 3,
        score: 82,
        tierRank: "A",
        reasonTh: "แก้ปัญหามานาไม่พอ หรือสลับเพิ่มเลือดเอาตัวรอด",
        reasonEn: "Solves mana starvation or converts to extra HP in pinches.",
        statsSummary: "Mana/HP Ratio Toggle",
      },
      {
        key: "elven_tunic",
        displayName: "Elven Tunic",
        tier: 3,
        score: 76,
        tierRank: "A",
        reasonTh: "+16% หลบหลีก และ +7% วิ่งเร็ว ปลอดภัยจากตัวตีประชิด",
        reasonEn: "+16% Evasion and +7% move speed.",
        statsSummary: "+16% Evasion, +7% MS",
      },
      {
        key: "mind_breaker",
        displayName: "Mind Breaker",
        tier: 3,
        score: 70,
        tierRank: "B",
        reasonTh: "โจมตีเพื่อใบ้ขัดจังหวะสกิลร่ายของศัตรู",
        reasonEn: "Attacks apply 1.5s silence.",
        statsSummary: "+25 AS, 1.5s Silence",
      },
    ],
    UniversalAllRounder: [
      {
        key: "paladin_sword",
        displayName: "Paladin Sword",
        tier: 3,
        score: 95,
        tierRank: "S",
        reasonTh: "+16 ดาเมจ ดูดเลือด และบัฟการฮีล 14%",
        reasonEn: "+16 Dmg, +8% Lifesteal, heal/lifesteal amp.",
        statsSummary: "+16 Dmg, Lifesteal Amp",
      },
      {
        key: "mind_breaker",
        displayName: "Mind Breaker",
        tier: 3,
        score: 92,
        tierRank: "S",
        reasonTh: "+25 ความเร็วตี และตีติดใบ้ 1.5 วินาที",
        reasonEn: "+25 AS, attacks silence target for 1.5s.",
        statsSummary: "+25 AS, 1.5s Silence on Hit",
      },
      {
        key: "psychic_headband",
        displayName: "Psychic Headband",
        tier: 3,
        score: 86,
        tierRank: "A",
        reasonTh: "+12% Int, ระยะร่าย และสกิลผลักศัตรู",
        reasonEn: "+12% Int, cast range, and push active.",
        statsSummary: "+12% Int, Cast Range, Push Active",
      },
      {
        key: "elven_tunic",
        displayName: "Elven Tunic",
        tier: 3,
        score: 82,
        tierRank: "A",
        reasonTh: "หลบหลีก 16%, วิ่งเร็ว 7% และตีไว 26",
        reasonEn: "+16% Evasion, +7% MS, +26 AS.",
        statsSummary: "+16% Evasion, +7% MS, +26 AS",
      },
      {
        key: "nemesis_curse",
        displayName: "Nemesis Curse",
        tier: 3,
        score: 75,
        tierRank: "B",
        reasonTh: "+35 ดาเมจ และคำสาปเพิ่มดาเมจ",
        reasonEn: "+35 Damage with damage amplification.",
        statsSummary: "+35 Dmg, Damage Curse",
      },
    ],
  },

  // === TIER 4 (37:00) ===
  4: {
    PhysicalCarryMelee: [
      {
        key: "ninja_gear",
        displayName: "Ninja Gear",
        tier: 4,
        score: 98,
        tierRank: "S",
        reasonTh: "+24 Agility, +5% วิ่งเร็ว และกด Solo Smoke ล่องหนเดี่ยว แอบดักแก๊งหรือดันป้อมเลทเกม",
        reasonEn: "+24 Agility, +5% MS, active casts Solo Smoke. Unmatched split-push and pickoff weapon.",
        statsSummary: "+24 Agi, Solo Smoke Active",
      },
      {
        key: "avianas_feather",
        displayName: "Aviana's Feather",
        tier: 4,
        score: 92,
        tierRank: "S",
        reasonTh: "+25% หลบหลีก, +30 วิ่งเร็ว และบินข้ามสิ่งกีดขวางเมื่อเลือดต่ำกว่า 30% เอาตัวรอดได้ชัวร์",
        reasonEn: "+25% Evasion, +30 MS, flying movement below 30% HP. Guaranteed clutch escapes.",
        statsSummary: "+25% Evasion, +30 MS, Flying Escape",
      },
      {
        key: "ancient_guardian",
        displayName: "Ancient Guardian",
        tier: 4,
        score: 84,
        tierRank: "A",
        reasonTh: "+50 ดาเมจมหาศาล โหดมากตอนไฟต์กันใกล้ป้อมหรือบุกขึ้นบ้านศัตรู",
        reasonEn: "+50 Huge attack damage, especially near ancient and high-ground towers.",
        statsSummary: "+50 Attack Damage",
      },
      {
        key: "havoc_hammer",
        displayName: "Havoc Hammer",
        tier: 4,
        score: 80,
        tierRank: "A",
        reasonTh: "+14 Strength, +30 ดาเมจ และกดผลักศัตรูกระเด็นรอบตัวพร้อมระเบิดเวท 275 ดาเมจ",
        reasonEn: "+14 Str, +30 Dmg, active knockback & 275 damage burst.",
        statsSummary: "+14 Str, +30 Dmg, Knockback Active",
      },
      {
        key: "trickster_cloak",
        displayName: "Trickster Cloak",
        tier: 4,
        score: 72,
        tierRank: "B",
        reasonTh: "+20% หลบหลีก, +20% กันเวท และกดล่องหน 6 วินาที",
        reasonEn: "+20% Evasion, +20% Magic resist, 6s Invisibility active.",
        statsSummary: "+20% Evasion/MR, Invisibility Active",
      },
    ],
    PhysicalCarryRanged: [
      {
        key: "telescope",
        displayName: "Telescope",
        tier: 4,
        score: 98,
        tierRank: "S",
        reasonTh: "+125 ระยะยิงและระยะร่ายสกิลให้ตนเองและเพื่อน ยืนยิงไกลนอกจอศัตรูเข้าไม่ถึง",
        reasonEn: "+125 Attack & Cast Range aura to team. Snipes enemies completely outside their reach.",
        statsSummary: "+125 Attack/Cast Range Aura",
      },
      {
        key: "ninja_gear",
        displayName: "Ninja Gear",
        tier: 4,
        score: 90,
        tierRank: "S",
        reasonTh: "+24 Agility และสกิลสโมคล่องหน จัดการเดินเกมและหลบวอร์ด",
        reasonEn: "+24 Agility and solo smoke active for perfect positioning.",
        statsSummary: "+24 Agi, Solo Smoke Active",
      },
      {
        key: "avianas_feather",
        displayName: "Aviana's Feather",
        tier: 4,
        score: 86,
        tierRank: "A",
        reasonTh: "+25% หลบหลีก และบินหนีเมื่อโดนไดฟ์ถึงตัว",
        reasonEn: "+25% Evasion and flying escape when dived.",
        statsSummary: "+25% Evasion, Flying at <30% HP",
      },
      {
        key: "ancient_guardian",
        displayName: "Ancient Guardian",
        tier: 4,
        score: 80,
        tierRank: "A",
        reasonTh: "+50 ดาเมจ ยิงถล่มป้อมและไฟต์บ้าน",
        reasonEn: "+50 Damage boost.",
        statsSummary: "+50 Attack Damage",
      },
      {
        key: "trickster_cloak",
        displayName: "Trickster Cloak",
        tier: 4,
        score: 74,
        tierRank: "B",
        reasonTh: "กดล่องหน 6 วินาทีเอาตัวรอด",
        reasonEn: "6s Invisibility active.",
        statsSummary: "Invisibility Active",
      },
    ],
    SpellCaster: [
      {
        key: "timeless_relic",
        displayName: "Timeless Relic",
        tier: 4,
        score: 98,
        tierRank: "S",
        reasonTh: "+15% ดาเมจเวทแรงขึ้น และ +20% สตั๊น/ดีบัฟอยู่นานขึ้น สกิลคอมโบชุดเดียวตาย",
        reasonEn: "+15% Spell Amp, +20% Debuff Duration Amp. Makes all nukes and disables lethal.",
        statsSummary: "+15% Spell Amp, +20% Debuff Amp",
      },
      {
        key: "telescope",
        displayName: "Telescope",
        tier: 4,
        score: 92,
        tierRank: "S",
        reasonTh: "+125 ระยะร่ายสกิลออร่าทั้งทีม สกิลเปิดและเก็บงานได้จากระยะปลอดภัยสุดๆ",
        reasonEn: "+125 Cast range aura for you and team. Keeps you safely out of initiation range.",
        statsSummary: "+125 Cast Range Aura",
      },
      {
        key: "stormcrafter",
        displayName: "Stormcrafter",
        tier: 4,
        score: 84,
        tierRank: "A",
        reasonTh: "+4 รีเจนมานา, ผ่าสายฟ้าใส่ศัตรูอัตโนมัติ และกดล้างดีบัฟวิ่งเร็ว 300 ทันที",
        reasonEn: "+4 Mana regen, passive lightning zaps, active basic dispel + 300 MS surge.",
        statsSummary: "+4 Mana Regen, Dispel + 300 MS Active",
      },
      {
        key: "trickster_cloak",
        displayName: "Trickster Cloak",
        tier: 4,
        score: 80,
        tierRank: "A",
        reasonTh: "+20% กันเวท, +20% หลบหลีก และกดหายตัว 6 วินาที ป้องกันการโดนเปิด",
        reasonEn: "+20% Evasion/Magic resist and 6s active invisibility.",
        statsSummary: "+20% Evasion/MR, Invisibility Active",
      },
      {
        key: "havoc_hammer",
        displayName: "Havoc Hammer",
        tier: 4,
        score: 70,
        tierRank: "B",
        reasonTh: "กดผลักศัตรูกระเด็นและสโลว์",
        reasonEn: "Knockback and magic damage burst.",
        statsSummary: "+14 Str, Knockback Burst",
      },
    ],
    TankInitiator: [
      {
        key: "havoc_hammer",
        displayName: "Havoc Hammer",
        tier: 4,
        score: 96,
        tierRank: "S",
        reasonTh: "+14 Strength, +30 ดาเมจ และกดผลักศัตรูรอบตัวกระเด็นพร้อมระเบิด 275 ดาเมจ ขัดจังหวะทั้งทีม",
        reasonEn: "+14 Str, +30 Dmg, active 275 damage knockback disrupting entire enemy formations.",
        statsSummary: "+14 Str, +30 Dmg, Knockback Active",
      },
      {
        key: "martyrs_plate",
        displayName: "Martyr's Plate",
        tier: 4,
        score: 92,
        tierRank: "S",
        reasonTh: "+20% กันเวท และดึงดาเมจจากเพื่อนรอบตัวมารับไว้เอง เซฟแครี่จากการโดนโฟกัสได้ดีเลิศ",
        reasonEn: "+20% Magic resist, redirects damage from nearby allies to self. Peak team saving tank.",
        statsSummary: "+20% MR, Damage Redirection Active",
      },
      {
        key: "ancient_guardian",
        displayName: "Ancient Guardian",
        tier: 4,
        score: 82,
        tierRank: "A",
        reasonTh: "+50 ดาเมจ ช่วยให้ฮีโร่สายแทงก์ตีเจ็บขึ้นอย่างมาก",
        reasonEn: "+50 Attack damage boost.",
        statsSummary: "+50 Attack Damage",
      },
      {
        key: "stormcrafter",
        displayName: "Stormcrafter",
        tier: 4,
        score: 78,
        tierRank: "A",
        reasonTh: "กดล้างสโลว์และวิ่งเร็ว 300 พุ่งเข้าเปิดไฟต์ไม่มีติดขัด",
        reasonEn: "Basic dispel + 300 MS active for unstoppable initiation.",
        statsSummary: "+4 Mana Regen, Dispel Active",
      },
      {
        key: "trickster_cloak",
        displayName: "Trickster Cloak",
        tier: 4,
        score: 70,
        tierRank: "B",
        reasonTh: "กันเวท 20% และกดล่องหน",
        reasonEn: "+20% Evasion and Magic resistance.",
        statsSummary: "+20% Evasion/MR",
      },
    ],
    SupportUtility: [
      {
        key: "telescope",
        displayName: "Telescope",
        tier: 4,
        score: 98,
        tierRank: "S",
        reasonTh: "+125 ระยะร่ายและระยะยิงให้ทั้งทีม ซัพพอร์ตยอดนิยมที่ช่วยให้ทีมได้เปรียบระยะตลอดเกม",
        reasonEn: "+125 Cast & Attack Range aura. Elite support neutral item that empowers the entire team.",
        statsSummary: "+125 Cast/Attack Range Aura",
      },
      {
        key: "timeless_relic",
        displayName: "Timeless Relic",
        tier: 4,
        score: 92,
        tierRank: "S",
        reasonTh: "+20% สตั๊นและดีบัฟอยู่นานขึ้น สกิลหยุดของซัพพอร์ตขังศัตรูจนตาย",
        reasonEn: "+20% Debuff duration amp. Stuns and silences last dramatically longer.",
        statsSummary: "+20% Debuff Duration, +15% Spell Amp",
      },
      {
        key: "trickster_cloak",
        displayName: "Trickster Cloak",
        tier: 4,
        score: 86,
        tierRank: "A",
        reasonTh: "กดล่องหน 6 วินาที หนีรอดจากการโดนแครี่ศัตรูกระโดดจับ",
        reasonEn: "6s Active invisibility with evasion & magic resist for reliable survival.",
        statsSummary: "+20% Evasion/MR, Invisibility Active",
      },
      {
        key: "stormcrafter",
        displayName: "Stormcrafter",
        tier: 4,
        score: 80,
        tierRank: "A",
        reasonTh: "กดล้างสโลว์และดีบัฟบนตัว วิ่งหนีรวดเร็ว",
        reasonEn: "Active self-dispel and move speed boost.",
        statsSummary: "Self-Dispel & 300 MS Active",
      },
      {
        key: "martyrs_plate",
        displayName: "Martyr's Plate",
        tier: 4,
        score: 72,
        tierRank: "B",
        reasonTh: "กันเวทและรับดาเมจแทนเพื่อน",
        reasonEn: "+20% Magic resist and ally damage redirection.",
        statsSummary: "+20% MR, Damage Redirection",
      },
    ],
    UniversalAllRounder: [
      {
        key: "ninja_gear",
        displayName: "Ninja Gear",
        tier: 4,
        score: 96,
        tierRank: "S",
        reasonTh: "+24 Agility (+16.8 Dmg), +5% MS และสกิล Solo Smoke",
        reasonEn: "+24 Agility (+16.8 Dmg) and solo smoke.",
        statsSummary: "+24 Agi, Solo Smoke Active",
      },
      {
        key: "telescope",
        displayName: "Telescope",
        tier: 4,
        score: 92,
        tierRank: "S",
        reasonTh: "+125 ระยะร่ายและระยะโจมตีออร่า",
        reasonEn: "+125 Cast & Attack Range aura.",
        statsSummary: "+125 Range Aura",
      },
      {
        key: "timeless_relic",
        displayName: "Timeless Relic",
        tier: 4,
        score: 84,
        tierRank: "A",
        reasonTh: "+15% ดาเมจเวท และ +20% ดีบัฟนานขึ้น",
        reasonEn: "+15% Spell Amp, +20% Debuff duration.",
        statsSummary: "+15% Spell Amp, +20% Debuff Amp",
      },
      {
        key: "havoc_hammer",
        displayName: "Havoc Hammer",
        tier: 4,
        score: 80,
        tierRank: "A",
        reasonTh: "+14 Str (+9.8 Dmg), +30 ดาเมจ และสกิลผลัก",
        reasonEn: "+14 Str, +30 Dmg, active knockback.",
        statsSummary: "+14 Str, +30 Dmg, Knockback",
      },
      {
        key: "avianas_feather",
        displayName: "Aviana's Feather",
        tier: 4,
        score: 74,
        tierRank: "B",
        reasonTh: "+25% หลบหลีก และบินหนีเมื่อเลือดน้อย",
        reasonEn: "+25% Evasion and flying escape.",
        statsSummary: "+25% Evasion, Flying Escape",
      },
    ],
  },

  // === TIER 5 (60:00) ===
  5: {
    PhysicalCarryMelee: [
      {
        key: "apex",
        displayName: "Apex",
        tier: 5,
        score: 99,
        tierRank: "S",
        reasonTh: "+70 สเตตัสหลัก (Agility/Strength) เพิ่มทั้งดาเมจ เลือด เกราะ และตีเร็วอย่างมหาศาล",
        reasonEn: "+70 Primary attribute. Tremendous boost to damage, armor, AS, and health.",
        statsSummary: "+70 Primary Attribute",
      },
      {
        key: "pirate_hat",
        displayName: "Pirate Hat",
        tier: 5,
        score: 96,
        tierRank: "S",
        reasonTh: "+150 ความเร็วโจมตี ตีรัวสะใจ ลบศัตรูหายในเสี้ยววินาที",
        reasonEn: "+150 Attack speed. Deletes enemy heroes in seconds with blinding attack speed.",
        statsSummary: "+150 Attack Speed",
      },
      {
        key: "mirror_shield",
        displayName: "Mirror Shield",
        tier: 5,
        score: 90,
        tierRank: "A",
        reasonTh: "สะท้อนสกิลล็อกเป้าของศัตรูทุก 8 วินาที ป้องกันการโดน Hex หรือสตั๊นปิดเกม",
        reasonEn: "Reflects targeted spells every 8s. Blocks game-ending hexes and single-target stuns.",
        statsSummary: "+10 All Stats, 75% Spell Reflection",
      },
      {
        key: "stygian_desolator",
        displayName: "Stygian Desolator",
        tier: 5,
        score: 84,
        tierRank: "A",
        reasonTh: "+60 ดาเมจ และการโจมตีลดเกราะศัตรู 10 หน่วย ตีบ้านและฮีโร่แหลก",
        reasonEn: "+60 Damage and -10 armor on hit. Devastates high-ground structures and heroes.",
        statsSummary: "+60 Damage, -10 Armor on Hit",
      },
      {
        key: "force_boots",
        displayName: "Force Boots",
        tier: 5,
        score: 75,
        tierRank: "B",
        reasonTh: "+115 ความเร็ววิ่ง และกดพุ่ง 750 หน่วยพร้อมล้างดีบัฟ",
        reasonEn: "+115 Move speed, active dispels and pushes 750 units.",
        statsSummary: "+115 MS, Dispel + Force Push",
      },
    ],
    PhysicalCarryRanged: [
      {
        key: "apex",
        displayName: "Apex",
        tier: 5,
        score: 99,
        tierRank: "S",
        reasonTh: "+70 สเตตัสหลัก ยิงแรงและตีไวสุดขีด",
        reasonEn: "+70 Primary attribute. Maximum ranged DPS and stats.",
        statsSummary: "+70 Primary Attribute",
      },
      {
        key: "pirate_hat",
        displayName: "Pirate Hat",
        tier: 5,
        score: 94,
        tierRank: "S",
        reasonTh: "+150 ความเร็วโจมตี ยิงถล่มศัตรูทั้งทีม",
        reasonEn: "+150 Attack speed. Unmatched machine-gun DPS.",
        statsSummary: "+150 Attack Speed",
      },
      {
        key: "mirror_shield",
        displayName: "Mirror Shield",
        tier: 5,
        score: 88,
        tierRank: "A",
        reasonTh: "สะท้อนสกิลล็อกเป้า ปลอดภัยจากการโดนกระโดดเปิด",
        reasonEn: "Spell reflection protects against long-range catches.",
        statsSummary: "+10 All Stats, Spell Reflection",
      },
      {
        key: "stygian_desolator",
        displayName: "Stygian Desolator",
        tier: 5,
        score: 84,
        tierRank: "A",
        reasonTh: "+60 ดาเมจ และลดเกราะ 10",
        reasonEn: "+60 Damage, -10 armor on hit.",
        statsSummary: "+60 Damage, -10 Armor",
      },
      {
        key: "force_boots",
        displayName: "Force Boots",
        tier: 5,
        score: 76,
        tierRank: "B",
        reasonTh: "วิ่งไวและกดพุ่งหนี",
        reasonEn: "High mobility and dispel.",
        statsSummary: "+115 MS, Dispel Active",
      },
    ],
    SpellCaster: [
      {
        key: "seer_stone",
        displayName: "Seer Stone",
        tier: 5,
        score: 99,
        tierRank: "S",
        reasonTh: "+350 ระยะร่ายสกิล, +350 วิชั่น และกดเปิดหมอกแมพ 5 วินาที สาดสกิลข้ามจอได้อย่างปลอดภัย",
        reasonEn: "+350 Cast range, +350 Vision, active reveals area. Cast catastrophic spells from across the map.",
        statsSummary: "+350 Cast Range, +350 Vision, Reveal Active",
      },
      {
        key: "mirror_shield",
        displayName: "Mirror Shield",
        tier: 5,
        score: 94,
        tierRank: "S",
        reasonTh: "สะท้อนสกิลล็อกเป้า ป้องกันไม่ให้โดนตัดจังหวะก่อนร่ายสกิลใหญ่",
        reasonEn: "Spell reflection stops enemy initiators from interrupting your big ultimates.",
        statsSummary: "+10 All Stats, Spell Reflection",
      },
      {
        key: "book_of_shadows",
        displayName: "Book of Shadows",
        tier: 5,
        score: 86,
        tierRank: "A",
        reasonTh: "+12 All Stats, +400 วิชั่นกลางคืน และกดเสกตนเองหรือเพื่อนเป็นอมตะ 4 วินาที",
        reasonEn: "+12 All stats, active renders target completely untargetable and invulnerable for 4s.",
        statsSummary: "+12 Stats, 4s Invulnerability Active",
      },
      {
        key: "apex",
        displayName: "Apex",
        tier: 5,
        score: 82,
        tierRank: "A",
        reasonTh: "+70 Intelligence มานามหาศาลและเวทแรงขึ้น",
        reasonEn: "+70 Intelligence, massive mana pool and spell amp.",
        statsSummary: "+70 Primary Attribute (Int)",
      },
      {
        key: "force_boots",
        displayName: "Force Boots",
        tier: 5,
        score: 75,
        tierRank: "B",
        reasonTh: "+115 ความเร็ววิ่ง และกดพุ่งล้างสถานะ",
        reasonEn: "Supreme positioning and self-dispel.",
        statsSummary: "+115 MS, Dispel Active",
      },
    ],
    TankInitiator: [
      {
        key: "giants_ring",
        displayName: "Giant's Ring",
        tier: 5,
        score: 99,
        tierRank: "S",
        reasonTh: "+35 Strength, +50 วิ่งเร็ว, ตัวใหญ่ขึ้น 100% เดินทะลุยูนิตและต้นไม้พร้อมเหยียบศัตรูทำดาเมจแรง",
        reasonEn: "+35 Str, +50 MS, 100% size, free pathing over terrain and stomps enemies for heavy damage.",
        statsSummary: "+35 Str, +50 MS, Stomp + Free Pathing",
      },
      {
        key: "mirror_shield",
        displayName: "Mirror Shield",
        tier: 5,
        score: 92,
        tierRank: "S",
        reasonTh: "สะท้อนสกิลล็อกเป้า ศัตรูใช้สกิลใส่จะโดนสกิลตัวเองสวนกลับทันที",
        reasonEn: "Reflects single-target disables back at enemy casters.",
        statsSummary: "+10 All Stats, Spell Reflection",
      },
      {
        key: "apex",
        displayName: "Apex",
        tier: 5,
        score: 86,
        tierRank: "A",
        reasonTh: "+70 Strength เพิ่มเลือดมหาศาลเกือบ 1,600 HP และดาเมจหนักหน่วง",
        reasonEn: "+70 Strength adds ~1540 max HP, enormous HP regen, and heavy base damage.",
        statsSummary: "+70 Primary Attribute (Str)",
      },
      {
        key: "stygian_desolator",
        displayName: "Stygian Desolator",
        tier: 5,
        score: 80,
        tierRank: "A",
        reasonTh: "+60 ดาเมจ และลดเกราะ 10",
        reasonEn: "+60 Damage, -10 armor on hit.",
        statsSummary: "+60 Damage, -10 Armor",
      },
      {
        key: "force_boots",
        displayName: "Force Boots",
        tier: 5,
        score: 74,
        tierRank: "B",
        reasonTh: "วิ่งไวและกดล้างสถานะ",
        reasonEn: "+115 Move speed and basic dispel.",
        statsSummary: "+115 MS, Dispel",
      },
    ],
    SupportUtility: [
      {
        key: "book_of_shadows",
        displayName: "Book of Shadows",
        tier: 5,
        score: 99,
        tierRank: "S",
        reasonTh: "กดเสกแครี่หรือตนเองเป็นอมตะและล็อกเป้าไม่ได้ 4 วินาที พลิกไฟต์ชี้ขาดเกม",
        reasonEn: "Makes target ally or self untargetable and invulnerable for 4s. Match-winning save.",
        statsSummary: "4s Invulnerability Active, +400 Night Vision",
      },
      {
        key: "seer_stone",
        displayName: "Seer Stone",
        tier: 5,
        score: 95,
        tierRank: "S",
        reasonTh: "+350 ระยะร่ายสกิล และกดเปิดวิชั่นตรวจเช็คศัตรู ป้องกันการโดนดักซุ่ม",
        reasonEn: "+350 Cast range, +350 vision and reveal active. Flawless vision control.",
        statsSummary: "+350 Cast Range, Area Reveal Active",
      },
      {
        key: "mirror_shield",
        displayName: "Mirror Shield",
        tier: 5,
        score: 88,
        tierRank: "A",
        reasonTh: "สะท้อนสกิลล็อกเป้า ป้องกันซัพพอร์ตโดนลอบสังหาร",
        reasonEn: "Reflects targeted spells to prevent being assassinated.",
        statsSummary: "+10 All Stats, Spell Reflection",
      },
      {
        key: "force_boots",
        displayName: "Force Boots",
        tier: 5,
        score: 82,
        tierRank: "A",
        reasonTh: "+115 วิ่งเร็ว และกดพุ่ง 750 หน่วยล้างสถานะ หนีรอดได้ทุกสถานการณ์",
        reasonEn: "+115 Move speed, active 750 push and dispel.",
        statsSummary: "+115 MS, 750 Push + Dispel",
      },
      {
        key: "giants_ring",
        displayName: "Giant's Ring",
        tier: 5,
        score: 72,
        tierRank: "B",
        reasonTh: "เพิ่มเลือดและความเร็วเดิน",
        reasonEn: "+35 Strength and free pathing.",
        statsSummary: "+35 Str, Free Pathing",
      },
    ],
    UniversalAllRounder: [
      {
        key: "apex",
        displayName: "Apex",
        tier: 5,
        score: 99,
        tierRank: "S",
        reasonTh: "+24 All Stats สำหรับฮีโร่ Universal = +50.4 ดาเมจ พร้อมเลือด เกราะ และมานาครบคุ้มที่สุด",
        reasonEn: "+24 All stats for Universal heroes yields +50.4 attack damage plus health, armor, and mana.",
        statsSummary: "+24 All Stats (+50.4 Dmg), All-around godhood",
      },
      {
        key: "pirate_hat",
        displayName: "Pirate Hat",
        tier: 5,
        score: 95,
        tierRank: "S",
        reasonTh: "+150 ความเร็วโจมตี ตีรวดเร็ว ดาเมจสูงลิ่ว",
        reasonEn: "+150 Attack speed to unleash massive Universal damage.",
        statsSummary: "+150 Attack Speed",
      },
      {
        key: "mirror_shield",
        displayName: "Mirror Shield",
        tier: 5,
        score: 90,
        tierRank: "A",
        reasonTh: "สะท้อนสกิลล็อกเป้า",
        reasonEn: "Spell reflection every 8s.",
        statsSummary: "+10 All Stats, Spell Reflection",
      },
      {
        key: "giants_ring",
        displayName: "Giant's Ring",
        tier: 5,
        score: 85,
        tierRank: "A",
        reasonTh: "+35 Strength, วิ่งเร็ว 50 และเดินเหยียบทำดาเมจ",
        reasonEn: "+35 Str, +50 MS, terrain walking.",
        statsSummary: "+35 Str, Free Pathing Stomp",
      },
      {
        key: "seer_stone",
        displayName: "Seer Stone",
        tier: 5,
        score: 76,
        tierRank: "B",
        reasonTh: "+350 ระยะร่าย และเปิดแมพ",
        reasonEn: "+350 Cast range and vision reveal.",
        statsSummary: "+350 Cast Range, Reveal",
      },
    ],
  },
};

export class NeutralAdvisorEngine {
  /**
   * Get recommendations for a specific tier and hero
   */
  public getRecommendations(
    heroNameOrKey: string,
    tier: number,
  ): NeutralItemRecommendation[] {
    const validTier = Math.max(1, Math.min(5, tier || 1));
    const { archetype } = getHeroArchetype(heroNameOrKey);
    const tierData = NEUTRAL_TIER_DATABASE[validTier];

    if (!tierData || !tierData[archetype]) {
      return NEUTRAL_TIER_DATABASE[1].PhysicalCarryMelee;
    }

    return tierData[archetype];
  }

  /**
   * Get all 5 tiers of recommendations for a hero
   */
  public getAllTierRecommendations(
    heroNameOrKey: string,
  ): Record<number, NeutralItemRecommendation[]> {
    const { archetype } = getHeroArchetype(heroNameOrKey);
    const result: Record<number, NeutralItemRecommendation[]> = {};

    for (let t = 1; t <= 5; t++) {
      result[t] = NEUTRAL_TIER_DATABASE[t][archetype];
    }

    return result;
  }
}

export const neutralAdvisor = new NeutralAdvisorEngine();
